<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
$path = trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/');
$base = trim(parse_url(config('base_url'), PHP_URL_PATH) ?? '', '/');
if ($base && str_starts_with($path, $base)) $path = trim(substr($path, strlen($base)), '/');
$page = max(1, int_param('page', 'get', 1));
$limit = (int)config('pagination_limit');
$offset = ($page - 1) * $limit;

if ($path === '' || $path === 'home') {
    $total=(int)(db_one("SELECT COUNT(*) c FROM posts WHERE status='published' AND publish_at<=NOW()")['c']??0);
    $posts=db_all("SELECT p.*, c.name category_name FROM posts p LEFT JOIN categories c ON c.id=p.category_id WHERE p.status='published' AND p.publish_at<=NOW() ORDER BY p.publish_at DESC LIMIT ? OFFSET ?",'ii',[$limit,$offset]);
    $popular=db_all("SELECT title,slug FROM posts WHERE status='published' ORDER BY views DESC LIMIT 5");
    $categories=db_all('SELECT name,slug FROM categories ORDER BY name');
    render('home', ['posts'=>$posts,'popular'=>$popular,'categories'=>$categories,'pagination'=>paginate($total, $page, $limit, pagination_base()),'meta_title'=>config('site_name')]);
} elseif ($path === 'register') {
    if(is_post()){ verify_csrf(); $u=input('username')??''; $eaddr=input('email',FILTER_VALIDATE_EMAIL)??''; $pass=$_POST['password']??''; $confirm=$_POST['confirm_password']??''; $errors=validate_required($_POST,['username','email','password','confirm_password']); if($m=validate_username($u))$errors['username']=$m; if($m=validate_email_address($eaddr))$errors['email']=$m; if($m=validate_password_pair($pass,$confirm))$errors['password']=$m; if(db_one('SELECT id FROM users WHERE username=?','s',[$u]))$errors['username']='Username already exists.'; if(db_one('SELECT id FROM users WHERE email=?','s',[$eaddr]))$errors['email']='Email already exists.'; if(!$errors){ mysqli_begin_transaction(db()); $role=(int)db_one("SELECT id FROM roles WHERE name='subscriber'")['id']; $uid=db_insert('INSERT INTO users (role_id, username, email, password_hash, status, email_verified, created_at, updated_at) VALUES (?,?,?,?,\'inactive\',0,NOW(),NOW())','isss',[$role,$u,$eaddr,password_hash($pass,PASSWORD_DEFAULT)]); [$plain,$hash]=random_token(); db_exec('INSERT INTO email_verification_tokens (user_id, token_hash, expires_at, created_at) VALUES (?,?,DATE_ADD(NOW(), INTERVAL ? SECOND),NOW())','isi',[$uid,$hash,config('security.verification_ttl')]); mysqli_commit(db()); send_email($eaddr,'Verify your email','Click <a href="'.e(url('verify?token='.$plain)).'">verify</a>.'); log_activity($uid,'registration','New account registered'); render('message',['title'=>'Check your email','message'=>'Registration successful. Verify your email to activate your account.']); } else render('auth/register',compact('errors','u','eaddr')); } else render('auth/register',['errors'=>[]]);
} elseif ($path === 'verify') {
    $hash=hash('sha256', query('token') ?? ''); $tok=db_one('SELECT * FROM email_verification_tokens WHERE token_hash=? AND used_at IS NULL','s',[$hash]); if(!$tok) error_page(400,'Invalid Token','Verification token is invalid or already used.'); if(strtotime($tok['expires_at'])<time()) error_page(400,'Expired Token','Verification token has expired.'); mysqli_begin_transaction(db()); db_exec("UPDATE users SET email_verified=1,status='active',updated_at=NOW() WHERE id=?",'i',[(int)$tok['user_id']]); db_exec('UPDATE email_verification_tokens SET used_at=NOW() WHERE id=?','i',[(int)$tok['id']]); mysqli_commit(db()); log_activity((int)$tok['user_id'],'email_verified','Account activated'); render('message',['title'=>'Email verified','message'=>'Your account is active.']);
} elseif ($path === 'login') {
    if(is_post()){ verify_csrf(); $email=input('email',FILTER_VALIDATE_EMAIL)??''; $pass=$_POST['password']??''; if(login_rate_limited($email)) error_page(429,'Too Many Requests','Too many failed login attempts.'); $user=db_one('SELECT * FROM users WHERE email=?','s',[$email]); $ok=$user && (!$user['locked_until']||strtotime($user['locked_until'])<time()) && (int)$user['email_verified']===1 && $user['status']==='active' && password_verify($pass,$user['password_hash']); record_login_attempt($email,(bool)$ok); if($ok){ login_user($user); redirect('admin'); } if($user){ db_exec('UPDATE users SET failed_login_count=failed_login_count+1, locked_until=IF(failed_login_count+1>=?,DATE_ADD(NOW(), INTERVAL ? MINUTE),locked_until) WHERE id=?','iii',[config('security.login_max_attempts'),config('security.lockout_minutes'),(int)$user['id']]); } log_activity($user['id']??null,'failed_login','Failed login for '.$email); render('auth/login',['error'=>'Invalid credentials, unverified account, inactive account, or locked account.']); } else render('auth/login');
} elseif ($path === 'logout') { logout_user(); redirect('login');
} elseif ($path === 'forgot-password') { if(is_post()){ verify_csrf(); $email=input('email',FILTER_VALIDATE_EMAIL)??''; $user=db_one('SELECT * FROM users WHERE email=?','s',[$email]); if($user){ [$plain,$hash]=random_token(); db_exec('INSERT INTO password_reset_tokens (user_id, token_hash, expires_at, created_at) VALUES (?,?,DATE_ADD(NOW(), INTERVAL ? SECOND),NOW())','isi',[(int)$user['id'],$hash,config('security.reset_ttl')]); send_email($email,'Password reset','Reset: <a href="'.e(url('reset-password?token='.$plain)).'">link</a>'); log_activity((int)$user['id'],'password_reset_requested','Reset email sent'); } render('message',['title'=>'Reset requested','message'=>'If the email exists, a reset link has been sent.']); } else render('auth/forgot');
} elseif ($path === 'reset-password') { $hash=hash('sha256', query('token') ?? ($_POST['token']??'')); $tok=db_one('SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL','s',[$hash]); if(!$tok || strtotime($tok['expires_at'])<time()) error_page(400,'Invalid Token','Reset token is invalid or expired.'); if(is_post()){ verify_csrf(); $pass=$_POST['password']??''; $err=validate_password_pair($pass,$_POST['confirm_password']??''); if(!$err){ mysqli_begin_transaction(db()); db_exec('UPDATE users SET password_hash=?,updated_at=NOW() WHERE id=?','si',[password_hash($pass,PASSWORD_DEFAULT),(int)$tok['user_id']]); db_exec('UPDATE password_reset_tokens SET used_at=NOW() WHERE id=?','i',[(int)$tok['id']]); db_exec('DELETE FROM sessions WHERE user_id=?','i',[(int)$tok['user_id']]); mysqli_commit(db()); log_activity((int)$tok['user_id'],'password_changed','Password reset completed'); render('message',['title'=>'Password updated','message'=>'Your password has been changed.']); } else render('auth/reset',['error'=>$err,'token'=>$_GET['token']??'']); } else render('auth/reset',['token'=>$_GET['token']??'']);
} elseif ($path === 'profile') { require_login(); $user=current_user(); if(is_post()){ verify_csrf(); $username=input('username')??''; $email=input('email',FILTER_VALIDATE_EMAIL)??''; $errors=[]; if($m=validate_username($username))$errors[]=$m; if($m=validate_email_address($email))$errors[]=$m; if(!$errors){ $pic=$user['profile_picture']; if(!empty($_FILES['profile_picture']['name'])){ delete_media($pic); $uploadError = null; $newPicture = save_image_upload($_FILES['profile_picture'], $uploadError); if ($newPicture) { $pic = $newPicture; } else { $errors[] = $uploadError ?: 'Profile image upload failed.'; } } if(isset($_POST['remove_picture'])){ delete_media($pic); $pic=null; } if(!$errors){ db_exec('UPDATE users SET username=?,email=?,profile_picture=?,updated_at=NOW() WHERE id=?','sssi',[$username,$email,$pic,(int)$user['id']]); log_activity((int)$user['id'],'profile_updated','Profile updated'); redirect('profile', 'Profile updated.'); } } } render('profile',['user'=>current_user(),'errors'=>$errors??[]]);
} elseif (str_starts_with($path,'category/')) { $slug=basename($path); $cat=db_one('SELECT * FROM categories WHERE slug=?','s',[$slug]); if(!$cat) error_page(404,'Not Found','Category not found.'); $posts=db_all("SELECT * FROM posts WHERE category_id=? AND status='published' ORDER BY publish_at DESC LIMIT ? OFFSET ?",'iii',[(int)$cat['id'],$limit,$offset]); render('category',compact('cat','posts'));
} elseif ($path === 'search') { $q=query('q')??''; $like='%'.$q.'%'; $posts=db_all("SELECT p.* FROM posts p LEFT JOIN categories c ON c.id=p.category_id WHERE p.status='published' AND (p.title LIKE ? OR p.meta_keywords LIKE ? OR c.name LIKE ?) LIMIT ? OFFSET ?",'sssii',[$like,$like,$like,$limit,$offset]); render('search',compact('q','posts'));
} elseif (str_starts_with($path,'post/')) { $slug=basename($path); $post=db_one("SELECT p.*, c.name category_name FROM posts p LEFT JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.status='published'",'s',[$slug]); if(!$post) error_page(404,'Not Found','Post not found.'); db_exec('UPDATE posts SET views=views+1 WHERE id=?','i',[(int)$post['id']]); $related=db_all("SELECT title,slug FROM posts WHERE category_id=? AND id<>? AND status='published' LIMIT 3",'ii',[(int)$post['category_id'],(int)$post['id']]); render('post',compact('post','related')+['meta_title'=>$post['meta_title']?:$post['title'],'meta_description'=>$post['meta_description'],'meta_keywords'=>$post['meta_keywords']]);
} else error_page(404,'Not Found','The requested page could not be found.');
