<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require_role(['admin','author','editor']);
$action=$_GET['action'] ?? 'dashboard'; $id=(int)($_GET['id'] ?? 0); $user=current_user();
if($action==='dashboard'){
 $stats=['users'=>db_one('SELECT COUNT(*) c FROM users')['c']??0,'posts'=>db_one('SELECT COUNT(*) c FROM posts')['c']??0,'published'=>db_one("SELECT COUNT(*) c FROM posts WHERE status='published'")['c']??0,'drafts'=>db_one("SELECT COUNT(*) c FROM posts WHERE status='draft'")['c']??0,'categories'=>db_one('SELECT COUNT(*) c FROM categories')['c']??0];
 $recentPosts=db_all('SELECT title,created_at FROM posts ORDER BY created_at DESC LIMIT 5'); $recentUsers=db_all('SELECT username,created_at FROM users ORDER BY created_at DESC LIMIT 5'); render('admin/dashboard',compact('stats','recentPosts','recentUsers','user'));
} elseif($action==='categories') { require_role(['admin','editor']); $q='%'.($_GET['q']??'').'%'; $cats=db_all('SELECT * FROM categories WHERE name LIKE ? ORDER BY name','s',[$q]); render('admin/categories',compact('cats'));
} elseif($action==='save_category') { require_role(['admin','editor']); verify_csrf(); $name=input('name')??''; $slug=unique_slug('categories', input('slug') ?: $name, $id); $desc=input('description')??''; if($id) db_exec('UPDATE categories SET name=?,slug=?,description=?,updated_at=NOW() WHERE id=?','sssi',[$name,$slug,$desc,$id]); else db_insert('INSERT INTO categories (name,slug,description,created_at,updated_at) VALUES (?,?,?,NOW(),NOW())','sss',[$name,$slug,$desc]); redirect('admin/?action=categories');
} elseif($action==='delete_category') { require_role('admin'); verify_csrf(); db_exec('DELETE FROM categories WHERE id=?','i',[$id]); redirect('admin/?action=categories');
} elseif($action==='posts') { $where=has_role('author')?'WHERE p.user_id='.(int)$user['id']:''; $posts=db_all("SELECT p.*,c.name category FROM posts p LEFT JOIN categories c ON c.id=p.category_id $where ORDER BY p.created_at DESC"); render('admin/posts',compact('posts'));
} elseif($action==='edit_post') { $post=$id?db_one('SELECT * FROM posts WHERE id=?','i',[$id]):null; if($post && has_role('author') && (int)$post['user_id']!==(int)$user['id']) error_page(403,'Forbidden','Authors can edit own posts only.'); $categories=db_all('SELECT * FROM categories ORDER BY name'); render('admin/post_form',compact('post','categories'));
} elseif($action==='save_post') { verify_csrf(); $title=input('title')??''; $slug=unique_slug('posts', input('slug') ?: $title, $id); $image=$_POST['existing_image']??null; if(!empty($_FILES['featured_image']['name'])) $image=save_image_upload($_FILES['featured_image']); $data=[$title,$slug,(int)$_POST['category_id'],$image,input('short_description')??'',$_POST['content']??'',input('meta_title')??'',input('meta_description')??'',input('meta_keywords')??'',($_POST['publish_date']??date('Y-m-d')).' '.($_POST['publish_time']??date('H:i:s')),in_array($_POST['status']??'draft',['draft','published'],true)?$_POST['status']:'draft']; if($id){ $post=db_one('SELECT * FROM posts WHERE id=?','i',[$id]); if($post && has_role('author') && (int)$post['user_id']!==(int)$user['id']) error_page(403,'Forbidden','Authors can update own posts only.'); db_exec('UPDATE posts SET title=?,slug=?,category_id=?,featured_image=?,short_description=?,content=?,meta_title=?,meta_description=?,meta_keywords=?,publish_at=?,status=?,updated_at=NOW() WHERE id=?','ssissssssssi',[...$data,$id]); } else db_insert('INSERT INTO posts (title,slug,category_id,featured_image,short_description,content,meta_title,meta_description,meta_keywords,publish_at,status,user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())','ssissssssssi',[...$data,(int)$user['id']]); redirect('admin/?action=posts');
} elseif($action==='delete_post') { verify_csrf(); $post=db_one('SELECT * FROM posts WHERE id=?','i',[$id]); if($post && has_role('author') && (int)$post['user_id']!==(int)$user['id']) error_page(403,'Forbidden','Authors can delete own posts only.'); db_exec('DELETE FROM posts WHERE id=?','i',[$id]); redirect('admin/?action=posts');
} elseif($action==='users') { require_role('admin'); $users=db_all('SELECT u.*,r.name role FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.created_at DESC'); render('admin/users',compact('users'));
} else error_page(404,'Not Found','Unknown admin action.');
